### ISSUE TITLE
Build error on windows (cannot find 'unistd.h')

### ISSUE THREAD

**Issue by rgrams** [JCash/defold-voronoi#1]
I just tried to use this, but it wouldn't build. It said "Cannot open include file: 'unistd.h': No such file or directory". I'm guessing this is a Windows vs. Mac issue? I would really appreciate a fix. Thanks!

**Comment by mathiaswking** [comment]
I have now updated the library to support Windows as well.

**Comment by rgrams** [comment]
Thanks a lot Mathias! Sorry to bug you!

**Comment by mathiaswking** [comment]
No problem!
It's just very nice that someone actually uses it :)
